import {
  House,
  Setting,
  User,
  UserFilled,
  OfficeBuilding,
  Menu,
  Lock,
  VideoCamera,
  Monitor,
  Cpu,
  Document,
  List,
  Folder,
  Files,
  Bell,
  DataAnalysis,
  Connection,
  Tools,
  Camera,
  Grid,
  Operation,
  Timer,
  Search,
  Histogram,
  Key,
  Tickets,
  Platform,
  Upload,
  Download,
  Warning,
  Calendar,
  Location,
} from '@element-plus/icons-vue'

export const iconCatalog = [
  { key: 'home', label: '首页', component: House },
  { key: 'settings', label: '设置', component: Setting },
  { key: 'user', label: '用户', component: User },
  { key: 'users', label: '成员', component: UserFilled },
  { key: 'department', label: '部门', component: OfficeBuilding },
  { key: 'menu', label: '菜单', component: Menu },
  { key: 'role', label: '角色权限', component: Lock },
  { key: 'video-camera', label: '视频', component: VideoCamera },
  { key: 'camera', label: '相机', component: Camera },
  { key: 'monitor', label: '监控', component: Monitor },
  { key: 'server', label: '服务信息', component: Cpu },
  { key: 'audit', label: '操作记录', component: Document },
  { key: 'list', label: '列表', component: List },
  { key: 'folder', label: '目录', component: Folder },
  { key: 'files', label: '文件', component: Files },
  { key: 'bell', label: '通知', component: Bell },
  { key: 'analysis', label: '分析', component: DataAnalysis },
  { key: 'connection', label: '连接', component: Connection },
  { key: 'tools', label: '工具', component: Tools },
  { key: 'grid', label: '应用', component: Grid },
  { key: 'operation', label: '操作', component: Operation },
  { key: 'timer', label: '计时', component: Timer },
  { key: 'search', label: '搜索', component: Search },
  { key: 'chart', label: '统计', component: Histogram },
  { key: 'key', label: '密钥', component: Key },
  { key: 'tickets', label: '工单', component: Tickets },
  { key: 'platform', label: '平台', component: Platform },
  { key: 'upload', label: '上传', component: Upload },
  { key: 'download', label: '下载', component: Download },
  { key: 'warning', label: '告警', component: Warning },
  { key: 'calendar', label: '日历', component: Calendar },
  { key: 'location', label: '位置', component: Location },
]

export function resolveIcon(key?: string | null) {
  return iconCatalog.find((icon) => icon.key === key)?.component || Menu
}
