-- GENERATED by scripts/export-sql.ps1. Do not edit directly.
-- 警告：将删除 sys_permission 表及全部数据，再重新建表。执行前请备份。
-- 仅用于独立开发/测试库；存在外部引用时DROP会被拒绝，请先处理依赖表。
-- 不得用于Flyway管理的应用库；DDL不能依赖事务回滚恢复。
SET NAMES utf8mb4;
SET time_zone = '+08:00';
SET FOREIGN_KEY_CHECKS = 1;

DROP TABLE IF EXISTS `sys_permission`;
CREATE TABLE sys_permission (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID，自增',
    code VARCHAR(96) NOT NULL COMMENT '唯一权限编码，例如system:user:read',
    name VARCHAR(64) NOT NULL COMMENT '权限显示名称',
    resource VARCHAR(64) NOT NULL COMMENT '所属资源分组，用于权限目录展示',
    description VARCHAR(255) NULL COMMENT '权限能力与使用边界说明',
    PRIMARY KEY (id),
    CONSTRAINT uq_permission_code UNIQUE (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限目录表，只登记已实现的后端功能权限';
CREATE INDEX ix_permission_resource ON sys_permission(resource);
