-- GENERATED by scripts/export-sql.ps1. Do not edit directly.
-- 警告：将删除 sys_user_role 表及全部数据，再重新建表。执行前请备份。
-- 仅用于独立开发/测试库；存在外部引用时DROP会被拒绝，请先处理依赖表。
-- 不得用于Flyway管理的应用库；DDL不能依赖事务回滚恢复。
SET NAMES utf8mb4;
SET time_zone = '+08:00';
SET FOREIGN_KEY_CHECKS = 1;

DROP TABLE IF EXISTS `sys_user_role`;
CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL COMMENT '用户ID，与角色ID组成联合主键',
    role_id BIGINT NOT NULL COMMENT '授予的角色ID，与用户ID组成联合主键',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '角色授予时间，UTC+8（北京时间）',
    created_by BIGINT NULL COMMENT '角色授予人用户ID，初始化时可为空',
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES sys_user(id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES sys_role(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关联表，仅个人赋权，不经部门继承';
CREATE INDEX ix_user_role_role ON sys_user_role(role_id, user_id);
