param([switch]$Check)

$ErrorActionPreference = 'Stop'
$sqlDirectory = Join-Path $PSScriptRoot '../platform-api/sql'
$migrationDirectory = Join-Path $sqlDirectory 'migrations'
$migrations = @(Get-ChildItem -LiteralPath $migrationDirectory -Filter 'V*__*.sql' |
    Sort-Object { [int]([regex]::Match($_.Name, '^V(\d+)__').Groups[1].Value) })
if ($migrations.Count -eq 0) { throw 'No versioned migrations found.' }

# Fold the already-applied V010 metadata into the original CREATE statements.
# This is a bounded conversion for V001-V008, not a general SQL migration parser.
$commentMigration = [IO.File]::ReadAllText((Join-Path $migrationDirectory 'V010__表和字段备注.sql'))
$tableComments = @{}
foreach ($block in [regex]::Matches($commentMigration, '(?s)/\*!80016 ALTER TABLE (\w+)\s+COMMENT = (''[^'']+''),(.*?)\*/;')) {
    $columns = @{}
    foreach ($column in [regex]::Matches($block.Groups[3].Value, 'MODIFY COLUMN (\w+) (.+?) COMMENT (''[^'']+'')')) {
        $columns[$column.Groups[1].Value] = @{
            Definition = $column.Groups[2].Value
            Comment = $column.Groups[3].Value
        }
    }
    $tableComments[$block.Groups[1].Value] = @{ Comment = $block.Groups[2].Value; Columns = $columns }
}
if ($tableComments.Count -ne 8) { throw 'Expected comments for all 8 initial tables.' }

# Apply the known timezone-comment revision to the generated CREATE statements.
$timezoneMigration = [IO.File]::ReadAllText((Join-Path $migrationDirectory 'V011__默认北京时间备注.sql'))
foreach ($block in [regex]::Matches($timezoneMigration, '(?s)/\*!80016 ALTER TABLE (\w+)\s+(.*?)\*/;')) {
    foreach ($column in [regex]::Matches($block.Groups[2].Value, 'MODIFY COLUMN (\w+) (.+?) COMMENT (''[^'']+'')')) {
        $existing = $tableComments[$block.Groups[1].Value].Columns[$column.Groups[1].Value]
        if (-not $existing -or $existing.Definition -cne $column.Groups[2].Value) { throw 'Timezone migration changed a column definition.' }
        $existing.Comment = $column.Groups[3].Value
    }
}

function Write-OrCheckSql([string]$Name, [string]$Content) {
    $expected = $Content.Replace("`r`n", "`n").TrimEnd() + "`n"
    $target = [IO.Path]::GetFullPath((Join-Path $sqlDirectory $Name))
    if ($Check) {
        if (-not (Test-Path -LiteralPath $target) -or
            [IO.File]::ReadAllText($target).Replace("`r`n", "`n") -cne $expected) {
            throw "$Name is stale. Run scripts/export-sql.ps1."
        }
    } else {
        [IO.File]::WriteAllText($target, $expected, [Text.UTF8Encoding]::new($false))
    }
}

$sections = @(
    '-- GENERATED by scripts/export-sql.ps1. Do not edit directly.'
    '-- 警告：重建脚本会删除以下8张业务表及全部数据，执行前请确认目标数据库并备份。'
    '-- Initial CREATE statements include column/table COMMENT inline.'
    '-- 仅用于独立开发/测试库重建，不得导入现有Flyway管理的应用数据库。'
    '-- 不删除数据库或Flyway历史；MySQL DDL不能依赖事务回滚恢复。'
    'SET NAMES utf8mb4;'
    "SET time_zone = '+08:00';"
    'SET FOREIGN_KEY_CHECKS = 1;'
    ''
)
$createSections = @()
$dropStatements = @()
$generatedTables = 0
foreach ($migration in $migrations) {
    $version = [int]([regex]::Match($migration.Name, '^V(\d+)__').Groups[1].Value)
    if ($version -in 10, 11) { continue }
    $sql = [IO.File]::ReadAllText($migration.FullName).Replace("`r`n", "`n").TrimEnd()
    if ($version -ge 1 -and $version -le 8) {
        $tableName = [regex]::Match($sql, '^CREATE TABLE (\w+)').Groups[1].Value
        $metadata = $tableComments[$tableName]
        if (-not $metadata) { throw "Missing table comments: $tableName" }
        foreach ($column in $metadata.Columns.GetEnumerator()) {
            $pattern = '(?m)^    ' + [regex]::Escape($column.Key + ' ' + $column.Value.Definition) + ',?$'
            $matches = [regex]::Matches($sql, $pattern)
            if ($matches.Count -ne 1) { throw "Column definition mismatch: $tableName.$($column.Key)" }
            $original = $matches[0].Value
            $sql = $sql.Replace($original, $original.TrimEnd(',') + ' COMMENT ' + $column.Value.Comment + ',')
        }
        $sql = $sql.Replace('DEFAULT CHARSET=utf8mb4;', 'DEFAULT CHARSET=utf8mb4 COMMENT=' + $metadata.Comment + ';')
        $name = $migration.Name -replace '^V\d+__', ''
        $drop = 'DROP TABLE IF EXISTS `{0}`;' -f $tableName
        $dropStatements = @($drop) + $dropStatements
        $singleTable = @(
            '-- GENERATED by scripts/export-sql.ps1. Do not edit directly.'
            "-- 警告：将删除 $tableName 表及全部数据，再重新建表。执行前请备份。"
            '-- 仅用于独立开发/测试库；存在外部引用时DROP会被拒绝，请先处理依赖表。'
            '-- 不得用于Flyway管理的应用库；DDL不能依赖事务回滚恢复。'
            'SET NAMES utf8mb4;'
            "SET time_zone = '+08:00';"
            'SET FOREIGN_KEY_CHECKS = 1;'
            ''
            $drop
            $sql
        )
        Write-OrCheckSql $name ($singleTable -join "`n")
        $generatedTables++
    }
    $createSections += "-- $($migration.Name -replace '^V\d+__', '')"
    $createSections += $sql
    $createSections += ''
}
if ($generatedTables -ne 8) { throw 'Expected all 8 initial CREATE statements.' }
$sections += '-- 先按逆依赖顺序删除，再按依赖顺序创建；保持外键检查开启。'
$sections += $dropStatements
$sections += ''
$sections += $createSections
Write-OrCheckSql '汇总.sql' ($sections -join "`n")
Write-Output "SQL exports checked/generated: 8 table files with inline COMMENT and one aggregate."
