param([switch]$Check)

$ErrorActionPreference = 'Stop'
$sqlDirectory = Join-Path $PSScriptRoot '../platform-api/sql'
$businessDirectory = Join-Path $sqlDirectory '业务'
# Dependency order only; table definitions and seed data live in these files.
$names = @('部门表.sql', '用户表.sql', '角色表.sql', '菜单表.sql',
    '用户角色关联表.sql', '用户部门关联表.sql', '角色菜单关联表.sql', '操作审计表.sql', 'IP封禁表.sql', '登录记录表.sql',
    '相机来源表.sql', '相机凭据表.sql', '相机端点表.sql', '视频分组表.sql',
    '相机设备表.sql', '相机通道表.sql', '相机码流表.sql', '相机码流定位表.sql', '相机创建回执表.sql',
    '账户相机范围表.sql', '账户视频组授权表.sql', '账户相机授权表.sql', '相机接入任务表.sql', '相机导入明细表.sql')
$actual = @(Get-ChildItem -LiteralPath $businessDirectory -Filter '*.sql' |
    Select-Object -ExpandProperty Name)
if (Compare-Object $names $actual) { throw 'Register every table file in dependency order before exporting.' }

$sections = @(
    '-- StreamFusion AI: complete schema and seeds for a new, dedicated empty database.'
    '-- Generated by scripts/export-sql.ps1; do not use for existing database upgrades.'
    'SET NAMES utf8mb4;'
    "SET time_zone = '+08:00';"
    'SET FOREIGN_KEY_CHECKS = 1;'
    ''
)
$drops = @()
$bodies = @()
$deferred = @()
$created = @{}
foreach ($name in $names) {
    $sql = [IO.File]::ReadAllText((Join-Path $businessDirectory $name)).Replace("`r`n", "`n")
    $parts = $sql -split '(?m)^-- DEFERRED CONSTRAINT\s*$', 2
    $sql = $parts[0]
    if ($parts.Count -gt 1) { $deferred += $parts[1].Trim() }
    # Each source has one DROP and one CREATE; preserve indexes, comments and seeds.
    $drop = [regex]::Matches($sql, '(?m)^DROP TABLE IF EXISTS \x60?(\w+)\x60?;\r?$')
    $create = [regex]::Matches($sql, '(?m)^CREATE TABLE (\w+)')
    if ($drop.Count -ne 1 -or $create.Count -ne 1 -or
        $drop[0].Groups[1].Value -cne $create[0].Groups[1].Value -or
        $drop[0].Index -gt $create[0].Index) { throw "Expected one matching DROP/CREATE: $name" }
    $table = $create[0].Groups[1].Value
    if ($created.ContainsKey($table)) { throw "Duplicate table: $table" }
    foreach ($reference in [regex]::Matches($sql, 'REFERENCES (\w+)')) {
        $parent = $reference.Groups[1].Value
        if ($parent -cne $table -and -not $created.ContainsKey($parent)) {
            throw "Wrong dependency order: $table references $parent"
        }
    }
    $created[$table] = $true
    $drops = @($drop[0].Value.Trim()) + $drops
    $bodies += "-- $name"
    $bodies += $sql.Substring($create[0].Index).TrimEnd()
    $bodies += ''

}
$deferredText = ($deferred -join "`n")
foreach ($reference in [regex]::Matches($deferredText, 'REFERENCES (\w+)')) {
    if (-not $created.ContainsKey($reference.Groups[1].Value)) { throw 'Unknown deferred FK target.' }
}
# Only the channel/default-profile cycle needs a deferred edge. Keep FK checks enabled.
$sections += @'
-- BEGIN MYSQL DEFERRED DROP
SET @camera_default_fk = (SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='camera_channel' AND CONSTRAINT_NAME='fk_camera_default_profile');
SET @camera_drop_sql = IF(@camera_default_fk > 0, 'ALTER TABLE camera_channel DROP FOREIGN KEY fk_camera_default_profile', 'SELECT 1');
PREPARE camera_drop_statement FROM @camera_drop_sql;
EXECUTE camera_drop_statement;
DEALLOCATE PREPARE camera_drop_statement;
-- END MYSQL DEFERRED DROP
'@
$sections += $drops
$sections += ''
$sections += $bodies
$sections += $deferred
$expected = (($sections -join "`n").TrimEnd() + "`n").Replace("`r`n", "`n")
$target = Join-Path $sqlDirectory 'streamfusion-mysql.sql'
if ($Check) {
    if (-not (Test-Path -LiteralPath $target) -or
        [IO.File]::ReadAllText($target).Replace("`r`n", "`n") -cne $expected) {
        throw 'streamfusion-mysql.sql is stale. Run scripts/export-sql.ps1.'
    }
} else {
    [IO.Directory]::CreateDirectory($sqlDirectory) | Out-Null
    [IO.File]::WriteAllText($target, $expected, [Text.UTF8Encoding]::new($false))
}

Write-Output "Complete SQL checked/generated from $($names.Count) table sources."
