SET NAMES utf8mb4;
SET time_zone = '+08:00';
SET FOREIGN_KEY_CHECKS = 1;

DROP TABLE IF EXISTS `camera_access_job`;
CREATE TABLE camera_access_job (
    id BIGINT NOT NULL COMMENT '发现任务雪花ID',
    actor_user_id BIGINT NOT NULL COMMENT '发起用户，不继承重建账号身份',
    actor_session_digest BINARY(32) NOT NULL COMMENT '发起会话HMAC，不保存明文会话ID',
    digest_key_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '会话和请求摘要密钥版本',
    client_request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '带时间戳的幂等请求键',
    request_fingerprint BINARY(32) NOT NULL COMMENT '请求HMAC',
    status VARCHAR(16) NOT NULL COMMENT 'QUEUED/RUNNING/SUCCEEDED/PARTIAL/FAILED/CANCELLED/EXPIRED',
    method VARCHAR(64) NOT NULL COMMENT '请求或实际识别的接入方式',
    job_kind VARCHAR(16) NOT NULL DEFAULT 'CATALOG' COMMENT 'CATALOG/SCAN/BULK_IMPORT',
    source_id BIGINT NULL COMMENT '显式复用或导入后的来源ID，无删除级联',
    source_version BIGINT NULL COMMENT '任务绑定的来源版本',
    bulk_group_id BIGINT NULL COMMENT '整批导入目标组，历史引用',
    bulk_next_page INT NOT NULL DEFAULT 1 COMMENT '整批导入下一页',
    bulk_total BIGINT NULL COMMENT '上游最近报告总量，不是全量快照',
    bulk_processed_count INT NOT NULL DEFAULT 0 COMMENT '已处理不同上游身份数',
    bulk_created_count INT NOT NULL DEFAULT 0 COMMENT '新建数',
    bulk_existing_count INT NOT NULL DEFAULT 0 COMMENT '匹配已有数',
    bulk_failed_count INT NOT NULL DEFAULT 0 COMMENT '逐项失败数，不含读取整页失败',
    bulk_duplicate_count INT NOT NULL DEFAULT 0 COMMENT '分页重复身份数',
    bulk_started_at DATETIME(6) NULL COMMENT '整批导入开始时间',
    version BIGINT NOT NULL DEFAULT 0 COMMENT '状态写入与取消围栏',
    encryption_key_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '暂存密钥版本',
    secret_nonce BINARY(12) NULL COMMENT 'AES-GCM nonce',
    secret_ciphertext MEDIUMBLOB NULL COMMENT '最大1MiB加密暂存；普通目录15分钟，整批30分钟',
    secret_tag BINARY(16) NULL COMMENT 'AES-GCM tag',
    reason_code VARCHAR(64) NULL COMMENT '固定安全诊断码，不存上游响应',
    origin_trace_id VARCHAR(64) NULL COMMENT '发起请求追踪ID',
    result_summary JSON NULL COMMENT '有界导入ID回执，不含凭据或URL',
    import_request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '导入幂等请求键',
    import_fingerprint BINARY(32) NULL COMMENT '导入版本及选集HMAC',
    created_at DATETIME(6) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(6) NOT NULL COMMENT '状态变化时间',
    expires_at DATETIME(6) NOT NULL COMMENT '目录和凭据保留期限',
    PRIMARY KEY (id),
    UNIQUE KEY uk_camera_access_request (actor_user_id,actor_session_digest,client_request_id),
    KEY ix_camera_access_expiry (expires_at,id),
    KEY ix_camera_access_actor (actor_user_id,created_at),
    KEY ix_camera_access_state (status,expires_at),
    CONSTRAINT ck_camera_access_status CHECK (status IN ('QUEUED','RUNNING','SUCCEEDED','PARTIAL','FAILED','CANCELLED','EXPIRED')),
    CONSTRAINT ck_access_job_kind CHECK (job_kind IN ('CATALOG','SCAN','BULK_IMPORT')),
    CONSTRAINT ck_access_job_bulk_counts CHECK (bulk_next_page BETWEEN 1 AND 101 AND (bulk_total IS NULL OR bulk_total >= 0) AND bulk_processed_count BETWEEN 0 AND 10000 AND bulk_created_count >= 0 AND bulk_existing_count >= 0 AND bulk_failed_count >= 0 AND bulk_duplicate_count >= 0 AND bulk_processed_count = bulk_created_count + bulk_existing_count + bulk_failed_count AND (source_version IS NULL OR source_version >= 0)),
    CONSTRAINT ck_camera_access_version CHECK (version>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='相机发现与有界整批导入任务';
